# Generated by Django 3.2.7 on 2021-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Person'),
        ),
    ]
